#!/bin/bash

help() {
  echo "Usage: $0 [-q] <log_file>"
  echo -e " -q \t Quiet run, skips warning messages and questions."
}

purge() {
 for i in ${TABLES} ; do
  if [ -z "${TABLE}" ]
  then
   TABLE=$i
   DB=''
  else
   DB=$i
   psql -d ${DB} -c "DROP SCHEMA ${TABLE} CASCADE;"
   TABLE=''
  fi
 done
}

# check arguments
if (( "$#" < 1 )) || [ "$1" == "-h" ]
then
  help
  exit 1
fi

# declare vars
QUIET=false
LOGFILE=''
TABLE=''
DB=''
OK=false

for i in $*; do 
 if [[ $i == "-q" ]]
 then
  QUIET=true
  OK=true
 else
  LOGFILE=$i
 fi
done

# get orphan tables and db names
TABLES=`grep 'autovacuum: found orphan temp table\|автоочистка: найдена устаревшая врем. таблица' ${LOGFILE} | grep -v '(null)' | grep -Po '\ "\K[^"]*' | paste  - - | sort | uniq`

# exit if nothing found
if [ -z "${TABLES}" ]
then
 ! ${QUIET} && echo "No orphan tables found!"
 exit 0
fi

if ! ${QUIET} 
then
 echo -e "Next tables will be removed: \nTABLE\t\tDB\n${TABLES}\nCAUTION! THIS CAN BE DANGEROUS! You must have a backup."
 read -p "Continue (y/n)" INPUT
 if [[ $INPUT == "Y" || $INPUT == "y" ]]; then
  OK=true
 fi
fi

if ${OK} 
then
 purge
 exit 0
else
 echo "Terminating."
 exit 1
fi

